package com.pranay.reproai.report

import com.google.gson.*
import com.pranay.reproai.tracking.EventSanitizer
import java.time.Instant

/** All outward formats pass through the same recursive sanitizer, including nested runner evidence. */
object IncidentReportExporter {
    private val gson = GsonBuilder().setPrettyPrinting().serializeNulls().create()
    private val outputGson = GsonBuilder().setPrettyPrinting().serializeNulls().create()
    private val identifierKeys=setOf("execution_id","executionId","scenario_id","scenarioId","reportId",
        "incidentId","sessionId","session_id","eventId","relevantEventIds","id")
    private val technicalIdentifier=Regex("(?:exec-[a-fA-F0-9]{32}|scen_(?:rotation_)?[a-fA-F0-9]{8}|RPA-[A-F0-9]{8}|[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12})")
    fun sanitized(report: IncidentReport): IncidentReport = gson.fromJson(clean(gson.toJsonTree(report)), IncidentReport::class.java)
    private fun clean(value: JsonElement, key: String = ""): JsonElement {
        if (EventSanitizer.isSensitiveKey(key)) return JsonPrimitive("[REDACTED_SECRET]")
        return when {
            value.isJsonObject -> JsonObject().apply { value.asJsonObject.entrySet().forEach { (k,v) ->
                // Gson cannot read an explicit JsonNull into a nullable JsonObject.
                // Omit only absent evidence containers; retain null state fields.
                if(!(v.isJsonNull && k in listOf("observed_state","setup_evidence")))
                    add(EventSanitizer.sanitizeText(k), clean(v,k))
            } }
            value.isJsonArray -> JsonArray().apply { value.asJsonArray.forEach { add(clean(it,key)) } }
            value.isJsonPrimitive && value.asJsonPrimitive.isString -> JsonPrimitive(
                if(key in identifierKeys && technicalIdentifier.matches(value.asString)) value.asString
                else EventSanitizer.sanitizeText(value.asString))
            else -> value.deepCopy()
        }
    }
    fun json(report: IncidentReport): String {
        val r = sanitized(report)
        return outputGson.toJson(linkedMapOf(
            "report" to linkedMapOf("reportId" to r.reportId, "incidentId" to r.incidentId, "createdAt" to r.createdAt,
                "issueTitle" to r.issueTitle, "description" to r.description, "status" to r.status, "likelyOwnerCategory" to r.likelyOwnerCategory),
            "session" to mapOf("id" to r.sessionId, "capturedAt" to r.environment.capturedAt), "environment" to r.environment,
            "evidence" to r.evidence, "analysis" to r.diagnosis, "reproduction" to r.reproduction,
            "execution" to r.execution, "verification" to r.verification, "artifacts" to r.artifacts))
    }
    fun summary(report: IncidentReport): String {
        val r = sanitized(report)
        return buildString {
            appendLine("ReproAI Incident Report - ${r.incidentId}")
            appendLine("Issue: ${r.issueTitle}")
            appendLine("Status: ${r.status}")
            if (r.description.isNotBlank()) appendLine("Description: ${r.description}")
            appendLine("Environment: ${r.environment.application ?: "Application unavailable"}; Android ${r.environment.androidVersion}; ${r.environment.manufacturer} ${r.environment.model}")
            if(r.environment.networkStrategy == "DEMOSHOP_DEMO_HOOK") appendLine("Network/payment evidence: deterministic DemoShop simulation (DEMOSHOP_DEMO_HOOK).")
            appendLine("Observed evidence: ${r.evidence.take(8).joinToString("; ") { it.title }}")
            r.diagnosis?.let { appendLine("Probable cause (inferred): ${it.probableCause}") }
            r.reproduction?.scenario?.steps?.forEachIndexed { i,s -> appendLine("${i+1}. ${s.description ?: listOfNotNull(s.action.name,s.target,s.value).joinToString(" ")}") }
            r.execution?.let { appendLine("Execution: ${it.outcome}; mode ${it.result.execution_mode}; ${it.result.execution_id}") }
            r.verification?.let {
                appendLine("Verification: ${it.execution.outcome}; mode ${it.execution.result.execution_mode}")
                appendLine("Before: ${it.originalFailure.joinToString().ifBlank { "Original execution unavailable" }}")
                appendLine("After: ${it.execution.observedSignature.joinToString().ifBlank { "Measured signature unavailable" }}")
                appendLine("Same recorded scenario: ${it.sameScenario ?: "Not available yet"}")
            }
            append("Generated by ReproAI")
        }
    }
    fun markdown(report: IncidentReport): String {
        val r = sanitized(report)
        fun safe(s: String) = s.replace("<", "&lt;").replace(">", "&gt;").replace("[", "\\[").replace("]", "\\]")
        return buildString {
            appendLine("# ReproAI Incident Report\n\n## Incident\n${r.incidentId}\n")
            appendLine("## Summary\n${safe(r.issueTitle)}\n\n${safe(r.description)}\n\nStatus: ${r.status}")
            appendLine("Likely category (inference, not guaranteed ownership): ${r.likelyOwnerCategory}\n")
            appendLine("## Environment")
            appendLine("- Device: ${safe(r.environment.manufacturer)} ${safe(r.environment.model)}")
            appendLine("- Android: ${safe(r.environment.androidVersion)}")
            appendLine("- Application: ${safe(r.environment.application ?: "Not available yet")}")
            appendLine("- Package: ${safe(r.environment.packageName ?: "Not available yet")}")
            appendLine("- Runner mode: ${r.environment.runnerMode ?: "Not available yet"}")
            appendLine("- Execution strategy: ${r.environment.networkStrategy ?: "Not available yet"}")
            if(r.environment.networkStrategy == "DEMOSHOP_DEMO_HOOK") appendLine("- Network/payment evidence: deterministic DemoShop simulation; physical radios unchanged.")
            appendLine("- Session: ${r.sessionId}")
            appendLine("- Captured: ${r.environment.capturedAt?.let { Instant.ofEpochMilli(it) } ?: "Not available yet"}\n")
            appendLine("## Evidence\nObserved events:")
            if (r.evidence.isEmpty()) appendLine("Not available yet")
            r.evidence.forEach { appendLine("- ${Instant.ofEpochMilli(it.timestamp)} | ${safe(it.source)} | ${it.type} | ${safe(it.title)}${if(it.description.isBlank()) "" else " - ${safe(it.description)}"}") }
            appendLine("\n## Diagnosis\nInferred from captured evidence:")
            r.diagnosis?.let {
                appendLine("Probable trigger: ${safe(it.probableTrigger)}\n\nProbable cause: ${safe(it.probableCause)}")
                appendLine("Evidence strength: ${strength(it.confidence)}\n\nRelevant components: ${it.relevantComponents.joinToString { c -> safe(c) }}")
            } ?: appendLine("Not available yet")
            appendLine("\n## Reproduction Steps")
            r.reproduction?.let {
                appendLine("Scenario: ${it.scenario.id} - ${safe(it.scenario.name)}")
                appendLine("Preconditions:")
                it.scenario.preconditions.forEach { p -> appendLine("- ${safe(p.type)}: ${safe(p.value)}") }
                it.scenario.steps.forEachIndexed { i,s -> appendLine("${i+1}. ${safe(listOfNotNull(s.action.name,s.target,s.value,s.description).joinToString(" - "))}") }
                appendLine("\nExpected: ${safe(it.expectedBehavior)}\n\nActual: ${safe(it.actualBehavior)}")
                appendLine("Assertions:")
                it.scenario.assertions.forEach { a -> appendLine("- ${a.type} ${safe(a.target.orEmpty())}: ${safe(a.expected)}") }
            } ?: appendLine("Not available yet")
            fun execution(e: ReportExecution) {
                appendLine("Outcome: ${e.outcome}\n\nExecution ID: ${e.result.execution_id}\n\nExecution mode: ${e.result.execution_mode}")
                appendLine("Device: ${safe(e.result.device_serial)}\n\nDuration: ${e.result.duration_ms} ms\n\nStep count: ${e.result.steps.size}")
                appendLine("Assertions: ${e.result.assertions_passed} matched / ${e.result.assertions_failed} unmatched")
                e.result.steps.filter { it.action.startsWith("ASSERT") }.forEach { appendLine("- ${it.action}: ${it.status} - ${safe(it.message)}") }
                appendLine("Measured signature: ${e.observedSignature.joinToString().ifBlank { "Not available yet" }}")
            }
            appendLine("\n## Execution Result")
            r.execution?.let { execution(it) } ?: appendLine("Not available yet")
            appendLine("\n## Verification")
            r.verification?.let {
                appendLine("Before: ${it.originalFailure.joinToString().ifBlank { "Original execution unavailable" }}")
                execution(it.execution)
                appendLine("Same recorded reproduction scenario: ${it.sameScenario ?: "Not available yet"}")
            } ?: appendLine("Not available yet")
            appendLine("\nGenerated by ReproAI")
        }
    }
    fun text(report: IncidentReport) = markdown(report).replace(Regex("(?m)^#{1,2} "), "")
    fun strength(confidence: Int) = when { confidence >= 80 -> "High"; confidence >= 50 -> "Moderate"; else -> "Low" }
}
